version: "3.8"

volumes:
  database_volume:
    driver: local

networks:
  php_basic:
    driver: bridge

services:
  app:
    build:
      context: .docker/php
    restart: no
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - php_basic
  database:
    image: 'mysql:8'
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - php_basic